spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        input:
          destination: demo-topic
          content-type: application/*+avro
          group: group-demo
        output:
          destination: demo-topic
          content-type: application/*+avro
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
            value.serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
            schema.registry.url: http://localhost:8081
          consumer-properties:
            key.serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
            value.serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
            schema.registry.url: http://localhost:8081
